// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvfjfgknavxadzmzmerd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2ZmpmZ2tuYXZ4YWR6bXptZXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDcxMzEsImV4cCI6MjA2ODUyMzEzMX0.phUvap_FFMYHLE2L9kKwEeYfyTzDmK0T50Acd7x2w1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});